basePath: /api/v1
definitions:
  dto.SyncScript:
    properties:
      action:
        type: string
      actiontime:
        type: integer
      msg:
        type: string
      script:
        $ref: '#/definitions/entity.SyncScript'
      uuid:
        type: string
    type: object
  dto.UserInfo:
    properties:
      avatar:
        type: string
      createtime:
        type: integer
      id:
        description: 用户id
        type: integer
      role:
        type: string
      updatetime:
        type: integer
      username:
        type: string
    type: object
  dto.WechatScanLogin:
    properties:
      code:
        type: string
      url:
        type: string
    type: object
  entity.SyncScript:
    properties:
      code:
        type: string
      createtime:
        type: integer
      device_id:
        type: integer
      meta_json:
        type: string
      name:
        type: string
      origin:
        type: string
      self_meta:
        type: string
      sort:
        type: integer
      state:
        type: integer
      type:
        type: integer
      updatetime:
        type: integer
      user_id:
        type: integer
      uuid:
        type: string
    type: object
  errs.JsonRespondError:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  repository.ScriptCatInfo:
    properties:
      notice:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  title: 云猫api文档
  version: "1.0"
paths:
  /account/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户登录
      operationId: login
      parameters:
      - description: 用户名/邮箱
        in: formData
        name: account
        required: true
        type: string
      - description: 登录密码
        in: formData
        name: password
        required: true
        type: string
      - description: 自动登录
        in: formData
        name: auto_login
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /account/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户注册
      operationId: register
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 登录密码
        in: formData
        name: password
        required: true
        type: string
      - description: 再输入一次登录密码
        in: formData
        name: repassword
        required: true
        type: string
      - description: 邮箱验证码
        in: formData
        name: email_verify_code
        type: string
      - description: 邀请码
        in: formData
        name: inv_code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /account/register/request-email-code:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 请求邮箱验证码
      operationId: request-email-code
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /auth/bbs:
    post:
      description: 论坛oauth2.0登录
      operationId: bbs-login
      responses:
        "302":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /auth/wechat:
    post:
      description: 微信oauth2.0登录
      operationId: wechat-login
      responses:
        "302":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /auth/wechat/request:
    post:
      description: 请求微信登录二维码
      operationId: wechat-request
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.WechatScanLogin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /auth/wechat/status:
    post:
      description: 查询微信扫码状态
      operationId: wechat-status
      parameters:
      - description: 重定向链接
        in: query
        name: redirect_uri
        type: string
      - description: 查询code
        in: formData
        name: code
        required: true
        type: string
      responses:
        "200":
          description: token
          schema:
            type: string
        "302":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 用户
      tags:
      - user
  /sync/{device}/script/pull/{version}:
    get:
      consumes:
      - application/json
      description: 拉取脚本变更
      operationId: sync-pull-script
      parameters:
      - description: 设备id
        in: path
        name: device
        required: true
        type: integer
      - description: 版本号
        in: path
        name: version
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SyncScript'
        "403":
          description: ""
      security:
      - BearerAuth: []
      summary: 同步
      tags:
      - sync
  /sync/{device}/script/push/{version}:
    put:
      consumes:
      - application/json
      description: 推送脚本变更,需要先拉取获得版本号
      operationId: sync-push-script
      parameters:
      - description: 设备id
        in: path
        name: device
        required: true
        type: integer
      - description: 版本号
        in: path
        name: version
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SyncScript'
        "403":
          description: ""
      security:
      - BearerAuth: []
      summary: 同步
      tags:
      - sync
  /system/version:
    get:
      consumes:
      - application/json
      description: 获取系统环境变量
      operationId: env
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.ScriptCatInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.JsonRespondError'
      summary: 系统环境
      tags:
      - system
  /user:
    get:
      description: 用户信息
      operationId: user-info
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserInfo'
        "403":
          description: ""
      summary: 用户
      tags:
      - user
  /user/avatar:
    get:
      description: 当前用户头像
      operationId: user-avatar
      responses:
        "200":
          description: ""
        "403":
          description: ""
      security:
      - BearerAuth: []
      summary: 用户
      tags:
      - user
    put:
      consumes:
      - multipart/form-data
      description: 更新用户头像
      operationId: user-update-avatar
      parameters:
      - description: 头像
        in: formData
        name: avatar
        required: true
        type: file
      responses:
        "200":
          description: ""
        "403":
          description: ""
      security:
      - BearerAuth: []
      summary: 用户
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
